name: Rust CE Functions
version: 0.1.0
description: Runtime for Rust CloudEvents functions
license: Apache-2.0
language: rust
maintainers:
  - name: Francesco Guardiani
    email: francescoguard@gmail.com
    github-id: slinkydeveloper
default-template: function